<?php

namespace Container8hfKO7u;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6D8b1kjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6D8b1kj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6D8b1kj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categories' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categories' => 'App\\Repository\\CategoriesRepository',
            'em' => '?',
        ]);
    }
}
