<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPsTEi4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPsTEi4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPsTEi4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPsTEi4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWPsTEi4\App_KernelDevDebugContainer([
    'container.build_hash' => 'WPsTEi4',
    'container.build_id' => '178386e2',
    'container.build_time' => 1606143149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPsTEi4');
