<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQxxLSI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQxxLSI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQxxLSI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQxxLSI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXQxxLSI\App_KernelDevDebugContainer([
    'container.build_hash' => 'XQxxLSI',
    'container.build_id' => '77de7cc9',
    'container.build_time' => 1606322509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQxxLSI');
